feat: fixed grep?

diff --git a/get-build-number/action.yml b/get-build-number/action.yml
--- a/get-build-number/action.yml
+++ b/get-build-number/action.yml
@@ -13,14 +13,21 @@ runs:
       name: Get Build Number
       shell: bash
       run: |
-        set -x
+        set -e
 
         BRANCH_NAME=${GITHUB_REF##*/}
         BRANCH_NAME=${BRANCH_NAME//\//-}
 
+        if [ -z "$BRANCH_NAME" ]; then
+          echo "::error::Could not retrive branch name"
+          exit 1
+        fi
+
         echo "::notice::BRANCH_NAME=$BRANCH_NAME"
 
-        BUILD_NUMBER=$(git tag | sort --version-sort | grep "$BRANCH_NAME" | tail -n 1 | awk -F. '{print $2}')
+        BUILD_NUMBER=$(git tag | sort --version-sort)
+        BUILD_NUMBER=$(echo "${BUILD_NUMBER}" | grep "$BRANCH_NAME" || true)
+        BUILD_NUMBER=$(echo "${BUILD_NUMBER}" | tail -n 1 | awk -F. '{print $2}')
         BUILD_NUMBER=$(echo "${BUILD_NUMBER}" | xargs echo -n)
 
         echo "::notice::BUILD_NUMBER=${BUILD_NUMBER}"
